[pytest]
DJANGO_SETTINGS_MODULE = lynxreactor.settings.dev
python_files = test_*.py tests.py
python_classes = Test*
python_functions = test_*
addopts =
    -v
    --strict-markers
    --tb=short
    --disable-warnings
    --reuse-db
testpaths =
    agency/tests