# Generated by Django 4.2.16 on 2026-09-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ['order'], 'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='section',
        ),
        migrations.AlterField(
            model_name='tariff',
            name='accent_color',
            field=models.CharField(blank=True, default='gold', help_text='gold, blue, green, purple, orange, red', max_length=20, verbose_name='Цвет акцента'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='description_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='development_time',
            field=models.CharField(default='Индивидуально', max_length=100, verbose_name='Время разработки'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='features',
            field=models.JSONField(blank=True, default=list, verbose_name='Особенности тарифа'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='icon',
            field=models.CharField(blank=True, default='fa-rocket', help_text='Font Awesome иконка, например: fa-rocket, fa-store, fa-crown', max_length=50, verbose_name='Иконка (CSS класс)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='is_custom',
            field=models.BooleanField(default=False, verbose_name='Индивидуальный тариф'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярный тариф'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название тарифа'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название тарифа'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название тарифа'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price_byn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена (BYN)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена (EUR)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price_rub',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена (RUB)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена (USD)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='site_format',
            field=models.CharField(blank=True, default='', help_text='Например: ЛЕНДИНГ / ПОСАДОЧНАЯ СТРАНИЦА', max_length=200, verbose_name='Формат сайта'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='site_format_en',
            field=models.CharField(blank=True, default='', help_text='Например: ЛЕНДИНГ / ПОСАДОЧНАЯ СТРАНИЦА', max_length=200, null=True, verbose_name='Формат сайта'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='site_format_ru',
            field=models.CharField(blank=True, default='', help_text='Например: ЛЕНДИНГ / ПОСАДОЧНАЯ СТРАНИЦА', max_length=200, null=True, verbose_name='Формат сайта'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL-псевдоним'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='subtitle',
            field=models.CharField(blank=True, default='', help_text='Краткое описание тарифа (1-2 предложения)', max_length=300, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='subtitle_en',
            field=models.CharField(blank=True, default='', help_text='Краткое описание тарифа (1-2 предложения)', max_length=300, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='subtitle_ru',
            field=models.CharField(blank=True, default='', help_text='Краткое описание тарифа (1-2 предложения)', max_length=300, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.DeleteModel(
            name='TariffsSection',
        ),
    ]
