# Generated by Django 4.2.16 on 2026-09-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_alter_tariff_options_remove_tariff_section_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ['order'], 'verbose_name': 'Tariff', 'verbose_name_plural': 'Tariffs'},
        ),
        migrations.AlterField(
            model_name='tariff',
            name='accent_color',
            field=models.CharField(blank=True, default='gold', help_text='gold, blue, green, purple, orange, red', max_length=20, verbose_name='Accent color'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='description_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='development_time',
            field=models.CharField(default='Individual', max_length=100, verbose_name='Development time'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='features',
            field=models.JSONField(blank=True, default=dict, help_text='{"ru": ["Особенность 1", "Особенность 2"], "en": ["Feature 1", "Feature 2"]}', verbose_name='Tariff features'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='icon',
            field=models.CharField(blank=True, default='fa-rocket', help_text='Font Awesome icon, e.g.: fa-rocket, fa-store, fa-crown', max_length=50, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='is_custom',
            field=models.BooleanField(default=False, verbose_name='Custom tariff'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Popular tariff'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tariff name'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Tariff name'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Tariff name'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price_byn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price (BYN)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price (EUR)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price_rub',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price (RUB)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price (USD)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='site_format',
            field=models.CharField(blank=True, default='', help_text='For example: LANDING / LANDING PAGE', max_length=200, verbose_name='Site format'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='site_format_en',
            field=models.CharField(blank=True, default='', help_text='For example: LANDING / LANDING PAGE', max_length=200, null=True, verbose_name='Site format'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='site_format_ru',
            field=models.CharField(blank=True, default='', help_text='For example: LANDING / LANDING PAGE', max_length=200, null=True, verbose_name='Site format'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL slug'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='subtitle',
            field=models.CharField(blank=True, default='', help_text='Brief description of the tariff (1-2 sentences)', max_length=300, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='subtitle_en',
            field=models.CharField(blank=True, default='', help_text='Brief description of the tariff (1-2 sentences)', max_length=300, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='subtitle_ru',
            field=models.CharField(blank=True, default='', help_text='Brief description of the tariff (1-2 sentences)', max_length=300, null=True, verbose_name='Subtitle'),
        ),
    ]
