# Generated by Django 4.2.16 on 2026-09-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_alter_tariff_options_alter_tariff_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='development_time_en',
            field=models.CharField(blank=True, default='', help_text='Leave empty to use the Russian version', max_length=100, verbose_name='Development time (EN)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='development_time',
            field=models.CharField(default='Individual', max_length=100, verbose_name='Development time (RU)'),
        ),
    ]
