# Generated by Django 4.2.16 on 2026-09-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_tariff_development_time_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='["tag1", "tag2", "tag3"]', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='techitem',
            name='category',
            field=models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('database', 'Database'), ('devops', 'DevOps'), ('other', 'Other')], default='backend', max_length=20, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='techitem',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Primary tech'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='LYNXREACTOR', max_length=100, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author_en',
            field=models.CharField(default='LYNXREACTOR', max_length=100, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author_ru',
            field=models.CharField(default='LYNXREACTOR', max_length=100, null=True, verbose_name='Author'),
        ),
    ]
