# Generated by Django 4.2.16 on 2026-09-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_blogpost_tags_techitem_category_techitem_is_primary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='image_dark',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='image_light',
        ),
        migrations.AddField(
            model_name='herosection',
            name='hero_image_dark_en',
            field=models.ImageField(blank=True, null=True, upload_to='hero/dark/en/', verbose_name='Hero Image Dark + EN'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='hero_image_dark_ru',
            field=models.ImageField(blank=True, null=True, upload_to='hero/dark/ru/', verbose_name='Hero Image Dark + RU'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='hero_image_light_en',
            field=models.ImageField(blank=True, null=True, upload_to='hero/light/en/', verbose_name='Hero Image Light + EN'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='hero_image_light_ru',
            field=models.ImageField(blank=True, null=True, upload_to='hero/light/ru/', verbose_name='Hero Image Light + RU'),
        ),
    ]
