# Generated by Django 4.2.16 on 2026-09-06 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_remove_herosection_image_dark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesssection',
            name='image_dark',
        ),
        migrations.RemoveField(
            model_name='businesssection',
            name='image_light',
        ),
        migrations.RemoveField(
            model_name='landingsection',
            name='feature_1_icon',
        ),
        migrations.RemoveField(
            model_name='landingsection',
            name='feature_1_text',
        ),
        migrations.RemoveField(
            model_name='landingsection',
            name='feature_1_text_en',
        ),
        migrations.RemoveField(
            model_name='landingsection',
            name='feature_1_text_ru',
        ),
        migrations.RemoveField(
            model_name='landingsection',
            name='feature_2_icon',
        ),
        migrations.RemoveField(
            model_name='landingsection',
            name='feature_2_text',
        ),
        migrations.RemoveField(
            model_name='landingsection',
            name='feature_2_text_en',
        ),
        migrations.RemoveField(
            model_name='landingsection',
            name='feature_2_text_ru',
        ),
        migrations.RemoveField(
            model_name='landingsection',
            name='feature_3_icon',
        ),
        migrations.RemoveField(
            model_name='landingsection',
            name='feature_3_text',
        ),
        migrations.RemoveField(
            model_name='landingsection',
            name='feature_3_text_en',
        ),
        migrations.RemoveField(
            model_name='landingsection',
            name='feature_3_text_ru',
        ),
        migrations.RemoveField(
            model_name='landingsection',
            name='feature_4_icon',
        ),
        migrations.RemoveField(
            model_name='landingsection',
            name='feature_4_text',
        ),
        migrations.RemoveField(
            model_name='landingsection',
            name='feature_4_text_en',
        ),
        migrations.RemoveField(
            model_name='landingsection',
            name='feature_4_text_ru',
        ),
        migrations.RemoveField(
            model_name='landingsection',
            name='image_dark',
        ),
        migrations.RemoveField(
            model_name='landingsection',
            name='image_light',
        ),
        migrations.RemoveField(
            model_name='refactorsection',
            name='image_dark',
        ),
        migrations.RemoveField(
            model_name='refactorsection',
            name='image_light',
        ),
        migrations.RemoveField(
            model_name='serviceitem',
            name='image_dark',
        ),
        migrations.RemoveField(
            model_name='serviceitem',
            name='image_light',
        ),
        migrations.AddField(
            model_name='businesssection',
            name='image_dark_en',
            field=models.ImageField(blank=True, null=True, upload_to='business/dark/en/', verbose_name='Image Dark + EN'),
        ),
        migrations.AddField(
            model_name='businesssection',
            name='image_dark_ru',
            field=models.ImageField(blank=True, null=True, upload_to='business/dark/ru/', verbose_name='Image Dark + RU'),
        ),
        migrations.AddField(
            model_name='businesssection',
            name='image_light_en',
            field=models.ImageField(blank=True, null=True, upload_to='business/light/en/', verbose_name='Image Light + EN'),
        ),
        migrations.AddField(
            model_name='businesssection',
            name='image_light_ru',
            field=models.ImageField(blank=True, null=True, upload_to='business/light/ru/', verbose_name='Image Light + RU'),
        ),
        migrations.AddField(
            model_name='landingsection',
            name='image_dark_en',
            field=models.ImageField(blank=True, null=True, upload_to='landing/dark/en/', verbose_name='Image Dark + EN'),
        ),
        migrations.AddField(
            model_name='landingsection',
            name='image_dark_ru',
            field=models.ImageField(blank=True, null=True, upload_to='landing/dark/ru/', verbose_name='Image Dark + RU'),
        ),
        migrations.AddField(
            model_name='landingsection',
            name='image_light_en',
            field=models.ImageField(blank=True, null=True, upload_to='landing/light/en/', verbose_name='Image Light + EN'),
        ),
        migrations.AddField(
            model_name='landingsection',
            name='image_light_ru',
            field=models.ImageField(blank=True, null=True, upload_to='landing/light/ru/', verbose_name='Image Light + RU'),
        ),
        migrations.AddField(
            model_name='refactorsection',
            name='image_dark_en',
            field=models.ImageField(blank=True, null=True, upload_to='refactor/dark/en/', verbose_name='Image Dark + EN'),
        ),
        migrations.AddField(
            model_name='refactorsection',
            name='image_dark_ru',
            field=models.ImageField(blank=True, null=True, upload_to='refactor/dark/ru/', verbose_name='Image Dark + RU'),
        ),
        migrations.AddField(
            model_name='refactorsection',
            name='image_light_en',
            field=models.ImageField(blank=True, null=True, upload_to='refactor/light/en/', verbose_name='Image Light + EN'),
        ),
        migrations.AddField(
            model_name='refactorsection',
            name='image_light_ru',
            field=models.ImageField(blank=True, null=True, upload_to='refactor/light/ru/', verbose_name='Image Light + RU'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='image_dark_en',
            field=models.ImageField(blank=True, null=True, upload_to='services/dark/en/', verbose_name='Image Dark + EN'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='image_dark_ru',
            field=models.ImageField(blank=True, null=True, upload_to='services/dark/ru/', verbose_name='Image Dark + RU'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='image_light_en',
            field=models.ImageField(blank=True, null=True, upload_to='services/light/en/', verbose_name='Image Light + EN'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='image_light_ru',
            field=models.ImageField(blank=True, null=True, upload_to='services/light/ru/', verbose_name='Image Light + RU'),
        ),
        migrations.CreateModel(
            name='LandingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('icon', models.CharField(default='fa-check', max_length=50, verbose_name='Icon')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('description_ru', models.CharField(max_length=200, null=True, verbose_name='Description')),
                ('description_en', models.CharField(max_length=200, null=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='agency.landingsection', verbose_name='Landing Section')),
            ],
            options={
                'verbose_name': 'Landing Feature',
                'verbose_name_plural': 'Landing Features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LandingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('icon', models.CharField(default='fa-search', max_length=50, verbose_name='Icon')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('description_ru', models.CharField(max_length=200, null=True, verbose_name='Description')),
                ('description_en', models.CharField(max_length=200, null=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='agency.landingsection', verbose_name='Landing Section')),
            ],
            options={
                'verbose_name': 'Landing Detail',
                'verbose_name_plural': 'Landing Details',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BusinessDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('icon', models.CharField(default='fa-search', max_length=50, verbose_name='Icon')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('description_ru', models.CharField(max_length=200, null=True, verbose_name='Description')),
                ('description_en', models.CharField(max_length=200, null=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='agency.businesssection', verbose_name='Business Section')),
            ],
            options={
                'verbose_name': 'Business Detail',
                'verbose_name_plural': 'Business Details',
                'ordering': ['order'],
            },
        ),
    ]
