# Generated by Django 4.2.16 on 2026-09-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_remove_businesssection_image_dark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetail',
            name='description',
        ),
        migrations.RemoveField(
            model_name='businessdetail',
            name='title',
        ),
        migrations.RemoveField(
            model_name='businessfeature',
            name='description',
        ),
        migrations.RemoveField(
            model_name='businessfeature',
            name='title',
        ),
        migrations.RemoveField(
            model_name='businesssection',
            name='cta_text',
        ),
        migrations.RemoveField(
            model_name='businesssection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='businesssection',
            name='label',
        ),
        migrations.RemoveField(
            model_name='businesssection',
            name='title',
        ),
        migrations.RemoveField(
            model_name='landingdetail',
            name='description',
        ),
        migrations.RemoveField(
            model_name='landingdetail',
            name='title',
        ),
        migrations.RemoveField(
            model_name='landingfeature',
            name='description',
        ),
        migrations.RemoveField(
            model_name='landingfeature',
            name='title',
        ),
        migrations.RemoveField(
            model_name='landingsection',
            name='cta_text',
        ),
        migrations.RemoveField(
            model_name='landingsection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='landingsection',
            name='label',
        ),
        migrations.RemoveField(
            model_name='landingsection',
            name='title',
        ),
        migrations.RemoveField(
            model_name='refactordetail',
            name='description',
        ),
        migrations.RemoveField(
            model_name='refactordetail',
            name='title',
        ),
        migrations.RemoveField(
            model_name='refactorfeature',
            name='text',
        ),
        migrations.RemoveField(
            model_name='refactorsection',
            name='cta_text',
        ),
        migrations.RemoveField(
            model_name='refactorsection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='refactorsection',
            name='label',
        ),
        migrations.RemoveField(
            model_name='refactorsection',
            name='title',
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='description_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Description EN'),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='description_ru',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Description RU'),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Title EN'),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Title RU'),
        ),
        migrations.AlterField(
            model_name='businessfeature',
            name='description_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Description EN'),
        ),
        migrations.AlterField(
            model_name='businessfeature',
            name='description_ru',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Description RU'),
        ),
        migrations.AlterField(
            model_name='businessfeature',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Title EN'),
        ),
        migrations.AlterField(
            model_name='businessfeature',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Title RU'),
        ),
        migrations.AlterField(
            model_name='businesssection',
            name='cta_text_en',
            field=models.CharField(default='Order Site', max_length=50, verbose_name='Button text EN'),
        ),
        migrations.AlterField(
            model_name='businesssection',
            name='cta_text_ru',
            field=models.CharField(default='Заказать сайт', max_length=50, verbose_name='Button text RU'),
        ),
        migrations.AlterField(
            model_name='businesssection',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Description EN'),
        ),
        migrations.AlterField(
            model_name='businesssection',
            name='description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Description RU'),
        ),
        migrations.AlterField(
            model_name='businesssection',
            name='label_en',
            field=models.CharField(default='E-COMMERCE', max_length=50, verbose_name='Label EN'),
        ),
        migrations.AlterField(
            model_name='businesssection',
            name='label_ru',
            field=models.CharField(default='ИНТЕРНЕТ-МАГАЗИНЫ', max_length=50, verbose_name='Label RU'),
        ),
        migrations.AlterField(
            model_name='businesssection',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title EN'),
        ),
        migrations.AlterField(
            model_name='businesssection',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title RU'),
        ),
        migrations.AlterField(
            model_name='landingdetail',
            name='description_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Description EN'),
        ),
        migrations.AlterField(
            model_name='landingdetail',
            name='description_ru',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Description RU'),
        ),
        migrations.AlterField(
            model_name='landingdetail',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Title EN'),
        ),
        migrations.AlterField(
            model_name='landingdetail',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Title RU'),
        ),
        migrations.AlterField(
            model_name='landingfeature',
            name='description_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Description EN'),
        ),
        migrations.AlterField(
            model_name='landingfeature',
            name='description_ru',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Description RU'),
        ),
        migrations.AlterField(
            model_name='landingfeature',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Title EN'),
        ),
        migrations.AlterField(
            model_name='landingfeature',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Title RU'),
        ),
        migrations.AlterField(
            model_name='landingsection',
            name='cta_text_en',
            field=models.CharField(default='Order Landing', max_length=50, verbose_name='Button text EN'),
        ),
        migrations.AlterField(
            model_name='landingsection',
            name='cta_text_ru',
            field=models.CharField(default='Заказать лендинг', max_length=50, verbose_name='Button text RU'),
        ),
        migrations.AlterField(
            model_name='landingsection',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Description EN'),
        ),
        migrations.AlterField(
            model_name='landingsection',
            name='description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Description RU'),
        ),
        migrations.AlterField(
            model_name='landingsection',
            name='label_en',
            field=models.CharField(default='LANDING PAGES', max_length=50, verbose_name='Label EN'),
        ),
        migrations.AlterField(
            model_name='landingsection',
            name='label_ru',
            field=models.CharField(default='ЛЕНДИНГИ', max_length=50, verbose_name='Label RU'),
        ),
        migrations.AlterField(
            model_name='landingsection',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title EN'),
        ),
        migrations.AlterField(
            model_name='landingsection',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title RU'),
        ),
        migrations.AlterField(
            model_name='refactordetail',
            name='description_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Description EN'),
        ),
        migrations.AlterField(
            model_name='refactordetail',
            name='description_ru',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Description RU'),
        ),
        migrations.AlterField(
            model_name='refactordetail',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Title EN'),
        ),
        migrations.AlterField(
            model_name='refactordetail',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Title RU'),
        ),
        migrations.AlterField(
            model_name='refactorfeature',
            name='text_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Text EN'),
        ),
        migrations.AlterField(
            model_name='refactorfeature',
            name='text_ru',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Text RU'),
        ),
        migrations.AlterField(
            model_name='refactorsection',
            name='cta_text_en',
            field=models.CharField(default='Order Audit', max_length=50, verbose_name='Button text EN'),
        ),
        migrations.AlterField(
            model_name='refactorsection',
            name='cta_text_ru',
            field=models.CharField(default='Заказать аудит', max_length=50, verbose_name='Button text RU'),
        ),
        migrations.AlterField(
            model_name='refactorsection',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Description EN'),
        ),
        migrations.AlterField(
            model_name='refactorsection',
            name='description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Description RU'),
        ),
        migrations.AlterField(
            model_name='refactorsection',
            name='label_en',
            field=models.CharField(default='REFACTORING & AUDIT', max_length=50, verbose_name='Label EN'),
        ),
        migrations.AlterField(
            model_name='refactorsection',
            name='label_ru',
            field=models.CharField(default='РЕФАКТОРИНГ И АУДИТ', max_length=50, verbose_name='Label RU'),
        ),
        migrations.AlterField(
            model_name='refactorsection',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title EN'),
        ),
        migrations.AlterField(
            model_name='refactorsection',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title RU'),
        ),
    ]
