# Generated by Django 4.2.16 on 2026-09-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_remove_businessdetail_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetail',
            name='description_en',
            field=models.CharField(default='Convenient catalog structure', max_length=200, verbose_name='Description EN'),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='description_ru',
            field=models.CharField(default='Удобная структура каталога', max_length=200, verbose_name='Description RU'),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='title_en',
            field=models.CharField(default='Product catalog', max_length=100, verbose_name='Title EN'),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='title_ru',
            field=models.CharField(default='Каталог товаров', max_length=100, verbose_name='Title RU'),
        ),
        migrations.AlterField(
            model_name='businessfeature',
            name='description_en',
            field=models.CharField(default='Full-fledged online trading', max_length=200, verbose_name='Description EN'),
        ),
        migrations.AlterField(
            model_name='businessfeature',
            name='description_ru',
            field=models.CharField(default='Полноценная онлайн-торговля', max_length=200, verbose_name='Description RU'),
        ),
        migrations.AlterField(
            model_name='businessfeature',
            name='title_en',
            field=models.CharField(default='Online store', max_length=100, verbose_name='Title EN'),
        ),
        migrations.AlterField(
            model_name='businessfeature',
            name='title_ru',
            field=models.CharField(default='Интернет-магазин', max_length=100, verbose_name='Title RU'),
        ),
        migrations.AlterField(
            model_name='businesssection',
            name='description_en',
            field=models.TextField(default='We create online stores and corporate websites with a well-thought-out structure, a convenient admin panel and full integration with payment systems.', verbose_name='Description EN'),
        ),
        migrations.AlterField(
            model_name='businesssection',
            name='description_ru',
            field=models.TextField(default='Создаём интернет-магазины и корпоративные сайты с продуманной структурой, удобной админ-панелью и полной интеграцией с системами оплаты.', verbose_name='Description RU'),
        ),
        migrations.AlterField(
            model_name='businesssection',
            name='title_en',
            field=models.CharField(default='A website for business that sells', max_length=200, verbose_name='Title EN'),
        ),
        migrations.AlterField(
            model_name='businesssection',
            name='title_ru',
            field=models.CharField(default='Сайт для бизнеса, который продаёт', max_length=200, verbose_name='Title RU'),
        ),
        migrations.AlterField(
            model_name='landingdetail',
            name='description_en',
            field=models.CharField(default='In-depth research of your target audience', max_length=200, verbose_name='Description EN'),
        ),
        migrations.AlterField(
            model_name='landingdetail',
            name='description_ru',
            field=models.CharField(default='Глубокое исследование вашей ЦА', max_length=200, verbose_name='Description RU'),
        ),
        migrations.AlterField(
            model_name='landingdetail',
            name='title_en',
            field=models.CharField(default='Target audience analysis', max_length=100, verbose_name='Title EN'),
        ),
        migrations.AlterField(
            model_name='landingdetail',
            name='title_ru',
            field=models.CharField(default='Анализ целевой аудитории', max_length=100, verbose_name='Title RU'),
        ),
        migrations.AlterField(
            model_name='landingfeature',
            name='description_en',
            field=models.CharField(default='Maximum conversion', max_length=200, verbose_name='Description EN'),
        ),
        migrations.AlterField(
            model_name='landingfeature',
            name='description_ru',
            field=models.CharField(default='Максимальная конверсия', max_length=200, verbose_name='Description RU'),
        ),
        migrations.AlterField(
            model_name='landingfeature',
            name='title_en',
            field=models.CharField(default='Focus on sales', max_length=100, verbose_name='Title EN'),
        ),
        migrations.AlterField(
            model_name='landingfeature',
            name='title_ru',
            field=models.CharField(default='Фокус на продажах', max_length=100, verbose_name='Title RU'),
        ),
        migrations.AlterField(
            model_name='landingsection',
            name='description_en',
            field=models.TextField(default='We create stylish one-page websites that focus attention, build trust and turn visitors into customers.', verbose_name='Description EN'),
        ),
        migrations.AlterField(
            model_name='landingsection',
            name='description_ru',
            field=models.TextField(default='Создаём стильные одностраничные сайты, которые фокусируют внимание, вызывают доверие и превращают посетителей в клиентов.', verbose_name='Description RU'),
        ),
        migrations.AlterField(
            model_name='landingsection',
            name='title_en',
            field=models.CharField(default='Development of high-converting landing pages', max_length=200, verbose_name='Title EN'),
        ),
        migrations.AlterField(
            model_name='landingsection',
            name='title_ru',
            field=models.CharField(default='Разработка продающих лендингов под ключ', max_length=200, verbose_name='Title RU'),
        ),
        migrations.AlterField(
            model_name='refactordetail',
            name='description_en',
            field=models.CharField(default='Code quality check and vulnerability search', max_length=200, verbose_name='Description EN'),
        ),
        migrations.AlterField(
            model_name='refactordetail',
            name='description_ru',
            field=models.CharField(default='Проверка качества кода и поиск уязвимостей', max_length=200, verbose_name='Description RU'),
        ),
        migrations.AlterField(
            model_name='refactordetail',
            name='title_en',
            field=models.CharField(default='Code audit', max_length=100, verbose_name='Title EN'),
        ),
        migrations.AlterField(
            model_name='refactordetail',
            name='title_ru',
            field=models.CharField(default='Аудит кода', max_length=100, verbose_name='Title RU'),
        ),
        migrations.AlterField(
            model_name='refactorfeature',
            name='text_en',
            field=models.CharField(default='Security', max_length=100, verbose_name='Text EN'),
        ),
        migrations.AlterField(
            model_name='refactorfeature',
            name='text_ru',
            field=models.CharField(default='Безопасность', max_length=100, verbose_name='Text RU'),
        ),
        migrations.AlterField(
            model_name='refactorsection',
            name='description_en',
            field=models.TextField(default='We conduct a deep audit of code, architecture and security. We identify bottlenecks, fix errors and optimize performance.', verbose_name='Description EN'),
        ),
        migrations.AlterField(
            model_name='refactorsection',
            name='description_ru',
            field=models.TextField(default='Проводим глубокий аудит кода, архитектуры и безопасности. Выявляем узкие места, исправляем ошибки и оптимизируем производительность.', verbose_name='Description RU'),
        ),
        migrations.AlterField(
            model_name='refactorsection',
            name='title_en',
            field=models.CharField(default='Security and performance audit of your Django project', max_length=200, verbose_name='Title EN'),
        ),
        migrations.AlterField(
            model_name='refactorsection',
            name='title_ru',
            field=models.CharField(default='Аудит безопасности и производительности вашего Django-проекта', max_length=200, verbose_name='Title RU'),
        ),
    ]
