# Generated by Django 4.2.16 on 2026-09-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_alter_businessdetail_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='title',
        ),
        migrations.RemoveField(
            model_name='portfoliosection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='portfoliosection',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='portfoliosection',
            name='title',
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='category_en',
            field=models.CharField(blank=True, default='Development', max_length=100, verbose_name='Category EN'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='category_ru',
            field=models.CharField(blank=True, default='Разработка', max_length=100, verbose_name='Category RU'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='description_en',
            field=models.TextField(blank=True, default='Project description', verbose_name='Description EN'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='description_ru',
            field=models.TextField(blank=True, default='Описание проекта', verbose_name='Description RU'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='title_en',
            field=models.CharField(default='Project name', max_length=200, verbose_name='Title EN'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='title_ru',
            field=models.CharField(default='Название проекта', max_length=200, verbose_name='Title RU'),
        ),
        migrations.AlterField(
            model_name='portfoliosection',
            name='description_en',
            field=models.TextField(default='View our projects and case studies', verbose_name='Description EN'),
        ),
        migrations.AlterField(
            model_name='portfoliosection',
            name='description_ru',
            field=models.TextField(default='Смотрите наши проекты и кейсы', verbose_name='Description RU'),
        ),
        migrations.AlterField(
            model_name='portfoliosection',
            name='subtitle_en',
            field=models.CharField(default='OUR WORKS', max_length=300, verbose_name='Subtitle EN'),
        ),
        migrations.AlterField(
            model_name='portfoliosection',
            name='subtitle_ru',
            field=models.CharField(default='НАШИ РАБОТЫ', max_length=300, verbose_name='Subtitle RU'),
        ),
        migrations.AlterField(
            model_name='portfoliosection',
            name='title_en',
            field=models.CharField(default='Websites we are proud of', max_length=200, verbose_name='Title EN'),
        ),
        migrations.AlterField(
            model_name='portfoliosection',
            name='title_ru',
            field=models.CharField(default='Сайты, которыми мы гордимся', max_length=200, verbose_name='Title RU'),
        ),
    ]
