# Generated by Django 4.2.16 on 2026-09-09 11:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0010_remove_portfolioitem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this post has been viewed', verbose_name='Views count'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Полное содержание поста', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_en',
            field=ckeditor.fields.RichTextField(help_text='Полное содержание поста', null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_ru',
            field=ckeditor.fields.RichTextField(help_text='Полное содержание поста', null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=ckeditor.fields.RichTextField(help_text='Краткое описание поста, отображается в списке блога', verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt_en',
            field=ckeditor.fields.RichTextField(help_text='Краткое описание поста, отображается в списке блога', null=True, verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt_ru',
            field=ckeditor.fields.RichTextField(help_text='Краткое описание поста, отображается в списке блога', null=True, verbose_name='Excerpt'),
        ),
    ]
