# Generated by Django 4.2.16 on 2026-09-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0011_blogpost_views_alter_blogpost_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='icon_png',
            field=models.ImageField(blank=True, help_text='Загрузите PNG иконку для категории (рекомендуемый размер: 64x64px)', null=True, upload_to='blog/categories/icons/', verbose_name='Icon PNG'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Font Awesome icon class, e.g. "fa-code", "fa-python", "fa-database"', max_length=50, verbose_name='Icon'),
        ),
    ]
