# Generated by Django 4.2.16 on 2026-09-10 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0012_blogcategory_icon_png_alter_blogcategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='dislikes',
            field=models.PositiveIntegerField(default=0, help_text='Number of dislikes', verbose_name='Dislikes'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='likes',
            field=models.PositiveIntegerField(default=0, help_text='Number of likes', verbose_name='Likes'),
        ),
        migrations.CreateModel(
            name='BlogPostVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10, verbose_name='Vote type')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='agency.blogpost', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Blog Post Vote',
                'verbose_name_plural': 'Blog Post Votes',
                'ordering': ['-created_at'],
                'unique_together': {('post', 'ip_address')},
            },
        ),
    ]
