# Generated by Django 4.2.16 on 2026-09-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0013_blogpost_dislikes_blogpost_likes_blogpostvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Загрузите PDF файл для скачивания (опционально)', null=True, upload_to='blog/pdfs/', verbose_name='PDF File'),
        ),
    ]
