# Generated by Django 4.2.16 on 2026-09-11 05:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0014_blogpost_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('page', models.CharField(choices=[('home', 'Home'), ('contacts', 'Contacts'), ('blog', 'Blog'), ('portfolio', 'Portfolio'), ('about', 'About')], max_length=20, unique=True, verbose_name='Page')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, default='', max_length=300, verbose_name='Subtitle')),
                ('subtitle_ru', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Subtitle')),
                ('subtitle_en', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Subtitle')),
                ('description', ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Description')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Description')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Description')),
                ('background_light', models.ImageField(blank=True, null=True, upload_to='mission/light/', verbose_name='Background Light Theme')),
                ('background_dark', models.ImageField(blank=True, null=True, upload_to='mission/dark/', verbose_name='Background Dark Theme')),
                ('button_text', models.CharField(blank=True, default='', max_length=50, verbose_name='Button text')),
                ('button_text_ru', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Button text')),
                ('button_text_en', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Button text')),
                ('button_url', models.CharField(blank=True, default='', max_length=200, verbose_name='Button URL')),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
            },
        ),
        migrations.AddField(
            model_name='contactpage',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='contact/about/', verbose_name='About Image'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='about_text',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='About Text'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='about_text_en',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='About Text'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='about_text_ru',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='About Text'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='about_title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='About Title'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='about_title_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='About Title'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='about_title_ru',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='About Title'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='linkedin',
            field=models.URLField(blank=True, default='', verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='max_messenger',
            field=models.URLField(blank=True, default='', verbose_name='MAX'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='pinterest',
            field=models.URLField(blank=True, default='', verbose_name='Pinterest'),
        ),
    ]
