# Generated by Django 4.2.16 on 2026-09-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0015_mission_contactpage_about_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('home', 'Главная'), ('contact', 'Контакты'), ('blog', 'Блог'), ('portfolio', 'Портфолио'), ('about', 'О нас'), ('services', 'Услуги'), ('pricing', 'Тарифы')], help_text='Уникальный идентификатор страницы', max_length=50, unique=True, verbose_name='Страница')),
                ('title_ru', models.CharField(blank=True, default='', help_text='Рекомендуемая длина: 50–60 символов', max_length=200, verbose_name='SEO Title (RU)')),
                ('description_ru', models.TextField(blank=True, default='', help_text='Рекомендуемая длина: 150–160 символов', max_length=500, verbose_name='SEO Description (RU)')),
                ('keywords_ru', models.TextField(blank=True, default='', help_text='Ключевые слова через запятую. Ориентировано на Яндекс.', verbose_name='SEO Keywords (RU)')),
                ('title_en', models.CharField(blank=True, default='', help_text='Рекомендуемая длина: 50–60 символов', max_length=200, verbose_name='SEO Title (EN)')),
                ('description_en', models.TextField(blank=True, default='', help_text='Рекомендуемая длина: 150–160 символов', max_length=500, verbose_name='SEO Description (EN)')),
                ('keywords_en', models.TextField(blank=True, default='', help_text='Ключевые слова через запятую', verbose_name='SEO Keywords (EN)')),
                ('og_title_ru', models.CharField(blank=True, default='', help_text='Если пусто — используется SEO Title', max_length=200, verbose_name='OG Title (RU)')),
                ('og_title_en', models.CharField(blank=True, default='', help_text='Если пусто — используется SEO Title', max_length=200, verbose_name='OG Title (EN)')),
                ('og_description_ru', models.TextField(blank=True, default='', help_text='Если пусто — используется SEO Description', max_length=500, verbose_name='OG Description (RU)')),
                ('og_description_en', models.TextField(blank=True, default='', help_text='Если пусто — используется SEO Description', max_length=500, verbose_name='OG Description (EN)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'SEO страницы',
                'verbose_name_plural': 'SEO страницы',
                'ordering': ['page_key'],
            },
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='seo_description_en',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='seo_description_ru',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='seo_title_en',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='seo_title_ru',
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='seo_description_en',
            field=models.CharField(blank=True, default='', help_text='Если пусто — используется SEO раздела «Блог»', max_length=500, verbose_name='SEO Description (EN)'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='seo_description_ru',
            field=models.CharField(blank=True, default='', help_text='Если пусто — используется SEO раздела «Блог»', max_length=500, verbose_name='SEO Description (RU)'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='seo_title_en',
            field=models.CharField(blank=True, default='', help_text='Если пусто — используется SEO раздела «Блог»', max_length=200, verbose_name='SEO Title (EN)'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='seo_title_ru',
            field=models.CharField(blank=True, default='', help_text='Если пусто — используется SEO раздела «Блог»', max_length=200, verbose_name='SEO Title (RU)'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='seo_description_en',
            field=models.CharField(blank=True, default='', help_text='Если пусто — используется SEO раздела «Портфолио»', max_length=500, verbose_name='SEO Description (EN)'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='seo_description_ru',
            field=models.CharField(blank=True, default='', help_text='Если пусто — используется SEO раздела «Портфолио»', max_length=500, verbose_name='SEO Description (RU)'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='seo_title_en',
            field=models.CharField(blank=True, default='', help_text='Если пусто — используется SEO раздела «Портфолио»', max_length=200, verbose_name='SEO Title (EN)'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='seo_title_ru',
            field=models.CharField(blank=True, default='', help_text='Если пусто — используется SEO раздела «Портфолио»', max_length=200, verbose_name='SEO Title (RU)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='seo_description_en',
            field=models.CharField(blank=True, default='', help_text='Если пусто — используется SEO раздела «Блог»', max_length=500, verbose_name='SEO Description (EN)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='seo_description_ru',
            field=models.CharField(blank=True, default='', help_text='Если пусто — используется SEO раздела «Блог»', max_length=500, verbose_name='SEO Description (RU)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='seo_title_en',
            field=models.CharField(blank=True, default='', help_text='Если пусто — используется SEO раздела «Блог»', max_length=200, verbose_name='SEO Title (EN)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='seo_title_ru',
            field=models.CharField(blank=True, default='', help_text='Если пусто — используется SEO раздела «Блог»', max_length=200, verbose_name='SEO Title (RU)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='["tag1", "tag2"]', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='features',
            field=models.JSONField(blank=True, default=dict, help_text='{"ru": ["Особенность 1"], "en": ["Feature 1"]}', verbose_name='Tariff features'),
        ),
    ]
