# Generated by Django 4.2.16 on 2026-09-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0016_pageseo_remove_blogpost_seo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageseo',
            name='page_key',
            field=models.CharField(choices=[('home', 'Главная'), ('contact', 'Контакты'), ('blog', 'Блог'), ('portfolio', 'Портфолио (секция главной)'), ('about', 'О нас (секция на /contact/)'), ('services', 'Услуги (секция главной)'), ('pricing', 'Тарифы (секция главной)')], help_text='Уникальный идентификатор страницы', max_length=50, unique=True, verbose_name='Страница'),
        ),
    ]
