# Generated by Django 4.2.16 on 2026-09-11 20:01

import agency.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0017_alter_pageseo_page_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blogpostvote',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='["tag1", "tag2"]', validators=[agency.validators.validate_tags], verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='technologies',
            field=models.JSONField(blank=True, default=list, validators=[agency.validators.validate_technologies], verbose_name='Technologies'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='features',
            field=models.JSONField(blank=True, default=dict, help_text='{"ru": ["Особенность 1"], "en": ["Feature 1"]}', validators=[agency.validators.validate_features], verbose_name='Tariff features'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['-published_at'], name='blog_pub_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['-views'], name='blog_views_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_published', 'is_active', '-published_at'], name='blog_pub_active_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['category', '-published_at'], name='blog_cat_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpostvote',
            index=models.Index(fields=['post', 'ip_address'], name='vote_post_ip_idx'),
        ),
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['-created_at'], name='contact_created_idx'),
        ),
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['status', '-created_at'], name='contact_status_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['-created_at'], name='portfolio_created_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['is_featured', 'is_active'], name='portfolio_featured_idx'),
        ),
        migrations.AddConstraint(
            model_name='blogpostvote',
            constraint=models.UniqueConstraint(fields=('post', 'ip_address'), name='unique_post_ip_vote'),
        ),
    ]
