# Generated by Django 4.2.16 on 2026-09-11 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0018_alter_blogpostvote_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author_ru',
        ),
    ]
