# Generated by Django 4.2.16 on 2026-09-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0019_remove_blogpost_author_en_remove_blogpost_author_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('source', models.CharField(blank=True, default='blog_detail', help_text='Откуда пришла подписка (blog_detail, footer и т.п.)', max_length=50, verbose_name='Source')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='subscriber_created_idx'), models.Index(fields=['is_active'], name='subscriber_active_idx')],
            },
        ),
    ]
