# Generated by Django 4.2.16 on 2026-09-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0020_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='last_emailed_at',
            field=models.DateTimeField(blank=True, help_text='Когда последний раз отправляли рассылку', null=True, verbose_name='Last emailed at'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='unsubscribe_token',
            field=models.CharField(blank=True, default='', help_text='Используется в ссылке для отписки', max_length=64, unique=True, verbose_name='Unsubscribe token'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, help_text='Когда подписчик отписался', null=True, verbose_name='Unsubscribed at'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='source',
            field=models.CharField(blank=True, default='blog_detail', help_text='Откуда пришла подписка (blog_detail, blog_list_sidebar, footer)', max_length=50, verbose_name='Source'),
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['unsubscribe_token'], name='subscriber_token_idx'),
        ),
    ]
