# Generated by Django 4.2.16 on 2026-09-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0021_subscriber_last_emailed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='about_image_dark_en',
            field=models.ImageField(blank=True, null=True, upload_to='contact/about/dark/en/', verbose_name='About Image Dark + EN'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='about_image_dark_ru',
            field=models.ImageField(blank=True, null=True, upload_to='contact/about/dark/ru/', verbose_name='About Image Dark + RU'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='about_image_light_en',
            field=models.ImageField(blank=True, null=True, upload_to='contact/about/light/en/', verbose_name='About Image Light + EN'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='about_image_light_ru',
            field=models.ImageField(blank=True, null=True, upload_to='contact/about/light/ru/', verbose_name='About Image Light + RU'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='about_label',
            field=models.CharField(blank=True, default='О КОМПАНИИ', help_text='Маленькая надпись над заголовком (RU)', max_length=100, verbose_name='About Label'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='about_label_en',
            field=models.CharField(blank=True, default='ABOUT US', help_text='Маленькая надпись над заголовком (EN)', max_length=100, verbose_name='About Label (EN)'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='about_subtitle',
            field=models.CharField(blank=True, default='', help_text='Краткое описание под заголовком', max_length=300, verbose_name='About Subtitle'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='contact/about/', verbose_name='About Image (fallback)'),
        ),
    ]
