# Generated by Django 4.2.16 on 2026-09-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0022_contactpage_about_image_dark_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='about_subtitle_en',
            field=models.CharField(blank=True, default='', help_text='Краткое описание под заголовком', max_length=300, null=True, verbose_name='About Subtitle'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='about_subtitle_ru',
            field=models.CharField(blank=True, default='', help_text='Краткое описание под заголовком', max_length=300, null=True, verbose_name='About Subtitle'),
        ),
    ]
