# Generated by Django 4.2.16 on 2026-09-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0023_contactpage_about_subtitle_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='whatsapp',
            field=models.URLField(blank=True, default='', verbose_name='WhatsApp'),
        ),
    ]
