# Generated by Django 4.2.30 on 2026-09-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0024_contactpage_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='turnstile_token',
            field=models.TextField(blank=True, default='', verbose_name='Turnstile token'),
        ),
    ]
