# Generated by Django 4.2.30 on 2026-09-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0025_alter_turnstile_token_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='address_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='address_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Address'),
        ),
    ]
