# Generated by Django 4.2.30 on 2026-09-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0026_add_address_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('contacts', 'Contacts'), ('blog', 'Blog'), ('blog_detail', 'Blog Detail (article page)'), ('portfolio', 'Portfolio'), ('about', 'About')], max_length=20, unique=True, verbose_name='Page'),
        ),
    ]
