# Generated by Django 4.2.30 on 2026-09-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0027_add_blog_detail_to_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], default='ru', help_text='Язык, на котором клиент отправил заявку', max_length=5, verbose_name='Language'),
        ),
    ]
