# Generated by Django 4.2.30 on 2026-09-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0028_contactrequest_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='referer',
            field=models.URLField(blank=True, max_length=2048, verbose_name='Referrer'),
        ),
    ]
