# Generated by Django 4.2.30 on 2026-09-16 18:36

import agency.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0029_alter_contactrequest_referer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Загрузите PDF файл для скачивания (опционально)', null=True, upload_to='blog/pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), agency.validators.validate_pdf_file], verbose_name='PDF File'),
        ),
    ]
