# Generated by Django 4.2.30 on 2026-09-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0030_alter_blogpost_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactrequest',
            name='turnstile_token',
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='turnstile_verified',
            field=models.BooleanField(default=False, help_text='Прошла ли заявка проверку Cloudflare Turnstile', verbose_name='Turnstile verified'),
        ),
    ]
