# Generated by Django 5.2.17 on 2026-09-17 18:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0031_remove_contactrequest_turnstile_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Полное содержание поста', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Полное содержание поста', null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Полное содержание поста', null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Краткое описание поста, отображается в списке блога', verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Краткое описание поста, отображается в списке блога', null=True, verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Краткое описание поста, отображается в списке блога', null=True, verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='about_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='About Text'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='about_text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='About Text'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='about_text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='About Text'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='Description'),
        ),
    ]
