# Generated by Django 5.2.17 on 2026-10-03 21:30

import agency.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0032_alter_blogpost_content_alter_blogpost_content_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='pdf_file_en',
            field=models.FileField(blank=True, help_text='Upload PDF file for download (EN version)', null=True, upload_to='blog/pdfs/en/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), agency.validators.validate_pdf_file], verbose_name='PDF File (EN)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='pdf_file_ru',
            field=models.FileField(blank=True, help_text='Загрузите PDF файл для скачивания (RU версия)', null=True, upload_to='blog/pdfs/ru/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), agency.validators.validate_pdf_file], verbose_name='PDF File (RU)'),
        ),
    ]
