# Generated by Django 5.2.17 on 2026-10-03 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0033_remove_blogpost_pdf_file_blogpost_pdf_file_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqitem',
            name='related_label_en',
            field=models.CharField(blank=True, default='', help_text="Link label (EN). If empty — 'Read more'", max_length=200, verbose_name='Link label (EN)'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='related_label_ru',
            field=models.CharField(blank=True, default='', help_text='Текст ссылки (RU). Если пусто — «Читать подробнее»', max_length=200, verbose_name='Link label (RU)'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='related_post',
            field=models.ForeignKey(blank=True, help_text='Выберите статью блога для перелинковки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_items', to='agency.blogpost', verbose_name='Related blog post'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='related_url',
            field=models.URLField(blank=True, default='', help_text='Или укажите внешнюю ссылку, если не выбрана статья', verbose_name='External URL'),
        ),
    ]
