# Generated by Django 5.2.17 on 2026-10-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0034_faqitem_related_label_en_faqitem_related_label_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='contract_amount_byn',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Итоговая сумма по договору. Заполняется менеджером.', max_digits=10, null=True, verbose_name='Contract amount (BYN)'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='invoiced_at',
            field=models.DateTimeField(blank=True, help_text='Когда отправлена ссылка на оплату', null=True, verbose_name='Invoiced at'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Когда оплата получена', null=True, verbose_name='Paid at'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='payment_status',
            field=models.CharField(choices=[('not_invoiced', 'Not invoiced'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='not_invoiced', max_length=20, verbose_name='Payment status'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='webpay_payment_url',
            field=models.URLField(blank=True, default='', help_text='Ссылка на оплату из ЛК WebPay.', max_length=500, verbose_name='WebPay payment URL'),
        ),
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['payment_status', '-created_at'], name='contact_payment_idx'),
        ),
    ]
